- hosts: all
  become: true
  roles:
   - role: commons

- hosts: routers
  become: true
  roles:
   - role: router

- hosts: red_interna
  become: true
  roles:
   - role: redinterna

- hosts: web
  become: true
  roles:
   - role: apache2

- hosts: bd
  become: true
  roles:
   - role: mariadb

